# LIN Protocol Constants
DEFAULT_SERIAL_PORT = '/dev/serial0'
DEFAULT_BAUD_RATE = 19200
DEFAULT_WAKEUP_PIN = 18

# LIN Frame constants
SYNC_BYTE = 0x55
BREAK_BYTE = 0x00
MAX_FRAME_DATA_LENGTH = 8

# Frame types
UNCONDITIONAL_FRAME = 0
EVENT_TRIGGERED_FRAME = 1
SPORADIC_FRAME = 2